<#
.SYNOPSIS
    Azure VM Cost Dashboard Export

.DESCRIPTION
    Builds an Excel dashboard workbook from the $allVMs and $allDisks collections
    generated by AzureVM-Inventory-Pricing.ps1. Includes KPI tiles, cost breakdowns,
    top spenders, and savings opportunities.
#>

#Requires -Modules ImportExcel

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [object[]]$AllVMs,

    [Parameter(Mandatory = $true)]
    [object[]]$AllDisks,

    [string]$OutputPath = "$env:USERPROFILE\Desktop\Azure_Cost_Dashboard_$(Get-Date -Format 'yyyyMMdd_HHmmss').xlsx",
    [string]$CurrencyCode = 'USD'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-ExcelColumn {
    param([int]$Col)
    $s = ''
    $d = [int]$Col
    while ($d -gt 0) {
        $m = [int](($d - 1) % 26)
        $s = [string][char](65 + $m) + $s
        $d = [int][math]::Floor(($d - $m) / 26)
    }
    return $s
}

function Set-CurrencyColumns {
    param(
        $Worksheet,
        [string[]]$Headers,
        [string[]]$Columns,
        [string]$Format = '$#,##0.00'
    )
    foreach ($name in $Columns) {
        $idx = [array]::IndexOf($Headers, $name)
        if ($idx -ge 0) {
            $Worksheet.Column([int]($idx + 1)).Style.Numberformat.Format = $Format
        }
    }
}

function Add-KpiTile {
    param(
        $Worksheet,
        [int]$Row,
        [int]$Col,
        [string]$Title,
        [object]$Value,
        [System.Drawing.Color]$BgColor,
        [System.Drawing.Color]$TextColor
    )

    $r1 = [int]$Row
    $r2 = [int]($Row + 1)
    $r3 = [int]($Row + 2)
    $c1 = [int]$Col

    $titleCell = $Worksheet.Cells[$r1, $c1]
    $titleCell.Value = $Title
    $titleCell.Style.Font.Bold = $true
    $titleCell.Style.Font.Size = 10
    $titleCell.Style.Font.Color.SetColor($TextColor)
    $titleCell.Style.HorizontalAlignment = [OfficeOpenXml.Style.ExcelHorizontalAlignment]::Center
    $titleCell.Style.VerticalAlignment   = [OfficeOpenXml.Style.ExcelVerticalAlignment]::Center
    $titleCell.Style.Fill.PatternType    = [OfficeOpenXml.Style.ExcelFillStyle]::Solid
    $titleCell.Style.Fill.BackgroundColor.SetColor($BgColor)

    $valueCell = $Worksheet.Cells[$r2, $c1]
    $valueCell.Value = $Value
    $valueCell.Style.Font.Bold = $true
    $valueCell.Style.Font.Size = 18
    $valueCell.Style.Font.Color.SetColor($TextColor)
    $valueCell.Style.HorizontalAlignment = [OfficeOpenXml.Style.ExcelHorizontalAlignment]::Center
    $valueCell.Style.VerticalAlignment   = [OfficeOpenXml.Style.ExcelVerticalAlignment]::Center
    $valueCell.Style.Fill.PatternType    = [OfficeOpenXml.Style.ExcelFillStyle]::Solid
    $valueCell.Style.Fill.BackgroundColor.SetColor($BgColor)

    $spacerCell = $Worksheet.Cells[$r3, $c1]
    $spacerCell.Style.Fill.PatternType = [OfficeOpenXml.Style.ExcelFillStyle]::Solid
    $spacerCell.Style.Fill.BackgroundColor.SetColor($BgColor)

    $Worksheet.Column($c1).Width = 18
}

# Normalize arrays
$vmList   = @($AllVMs)
$diskList = @($AllDisks)

if ($vmList.Count -eq 0) {
    throw 'AllVMs is empty. Run the inventory script first.'
}

# Metrics
$totalVMs         = $vmList.Count
$runningVMs       = @($vmList | Where-Object { $_.PowerState -match 'running' }).Count
$deallocatedVMs   = @($vmList | Where-Object { $_.PowerState -match 'deallocated' }).Count
$totalDisks       = $diskList.Count
$unattachedDisks  = @($diskList | Where-Object { $_.DiskState -match 'Unattached' }).Count
$subscriptionCnt  = @($vmList.SubscriptionName | Select-Object -Unique).Count

$vmMonthlyCost    = [math]::Round((($vmList   | Measure-Object -Property VMMonthlyPrice_USD      -Sum).Sum), 2)
$diskMonthlyCost  = [math]::Round((($diskList | Measure-Object -Property EstMonthlyPrice_USD     -Sum).Sum), 2)
$totalMonthlyCost = [math]::Round((($vmList   | Measure-Object -Property EstTotalMonthlyCost_USD -Sum).Sum), 2)
$annualEstimate   = [math]::Round(($totalMonthlyCost * 12), 2)

$deallocatedWaste = [math]::Round((
    ($vmList | Where-Object { $_.PowerState -match 'deallocated' } | Measure-Object -Property EstTotalDiskCost_USD -Sum).Sum
), 2)
if ($null -eq $vmMonthlyCost)    { $vmMonthlyCost = 0 }
if ($null -eq $diskMonthlyCost)  { $diskMonthlyCost = 0 }
if ($null -eq $totalMonthlyCost) { $totalMonthlyCost = 0 }
if ($null -eq $annualEstimate)   { $annualEstimate = 0 }
if ($null -eq $deallocatedWaste) { $deallocatedWaste = 0 }

# Aggregates
$costBySubscription = foreach ($g in ($vmList | Group-Object SubscriptionName)) {
    $name  = $g.Name
    $gvms  = @($g.Group)
    $gds   = @($diskList | Where-Object { $_.SubscriptionName -eq $name })

    $vmCost   = ($gvms | Measure-Object -Property VMMonthlyPrice_USD -Sum).Sum
    $diskCost = ($gds  | Measure-Object -Property EstMonthlyPrice_USD -Sum).Sum
    if ($null -eq $vmCost)   { $vmCost = 0 }
    if ($null -eq $diskCost) { $diskCost = 0 }

    [PSCustomObject]@{
        SubscriptionName = $name
        VMCount          = $gvms.Count
        DiskCount        = $gds.Count
        VMCost_USD       = [math]::Round([double]$vmCost, 2)
        DiskCost_USD     = [math]::Round([double]$diskCost, 2)
        TotalCost_USD    = [math]::Round(([double]$vmCost + [double]$diskCost), 2)
    }
} | Sort-Object TotalCost_USD -Descending

$costByRegion = foreach ($g in ($vmList | Group-Object Location)) {
    $region = $g.Name
    $gvms   = @($g.Group)
    $vmCost = ($gvms | Measure-Object -Property VMMonthlyPrice_USD      -Sum).Sum
    $tCost  = ($gvms | Measure-Object -Property EstTotalMonthlyCost_USD -Sum).Sum
    if ($null -eq $vmCost) { $vmCost = 0 }
    if ($null -eq $tCost)  { $tCost = 0 }
    [PSCustomObject]@{
        Region            = $region
        VMCount           = $gvms.Count
        VMCompute_USD     = [math]::Round([double]$vmCost, 2)
        TotalMonthly_USD  = [math]::Round([double]$tCost, 2)
    }
} | Sort-Object TotalMonthly_USD -Descending

$costByVmSize = foreach ($g in ($vmList | Group-Object VMSize)) {
    $size  = $g.Name
    $gvms  = @($g.Group)
    $cost  = ($gvms | Measure-Object -Property VMMonthlyPrice_USD -Sum).Sum
    $avg   = ($gvms | Measure-Object -Property VMMonthlyPrice_USD -Average).Average
    if ($null -eq $cost) { $cost = 0 }
    if ($null -eq $avg)  { $avg = 0 }
    [PSCustomObject]@{
        VMSize        = $size
        VMCount       = $gvms.Count
        TotalCost_USD = [math]::Round([double]$cost, 2)
        AvgCost_USD   = [math]::Round([double]$avg, 2)
    }
} | Sort-Object TotalCost_USD -Descending

$topExpensiveVMs = $vmList |
    Sort-Object EstTotalMonthlyCost_USD -Descending |
    Select-Object -First 10 SubscriptionName, ResourceGroup, VMName, Location, VMSize, PowerState,
        VMMonthlyPrice_USD, EstTotalDiskCost_USD, EstTotalMonthlyCost_USD

$savings = $vmList |
    Where-Object { $_.PowerState -match 'deallocated' -and $_.EstTotalDiskCost_USD -gt 0 } |
    Sort-Object EstTotalDiskCost_USD -Descending |
    Select-Object SubscriptionName, ResourceGroup, VMName, Location, VMSize, PowerState,
        EstTotalDiskCost_USD, Tags

# Workbook
$pkg = Open-ExcelPackage -Path $OutputPath -Create

# Theme colors
$darkBlue   = [System.Drawing.Color]::FromArgb(31, 78, 121)
$midBlue    = [System.Drawing.Color]::FromArgb(79, 129, 189)
$green      = [System.Drawing.Color]::FromArgb(0, 176, 80)
$red        = [System.Drawing.Color]::FromArgb(192, 0, 0)
$orange     = [System.Drawing.Color]::FromArgb(237, 125, 49)
$purple     = [System.Drawing.Color]::FromArgb(112, 48, 160)
$gray       = [System.Drawing.Color]::FromArgb(89, 89, 89)
$white      = [System.Drawing.Color]::White
$lightBlue  = [System.Drawing.Color]::FromArgb(221, 235, 247)

# Dashboard sheet
$wsDash = Add-Worksheet -ExcelPackage $pkg -WorksheetName 'Dashboard'
$wsDash.View.ShowGridLines = $false
$wsDash.Cells['A1:J1'].Merge = $true
$wsDash.Cells['A1'].Value = 'Azure Cost Dashboard'
$wsDash.Cells['A1'].Style.Font.Size = 22
$wsDash.Cells['A1'].Style.Font.Bold = $true
$wsDash.Cells['A1'].Style.Font.Color.SetColor($white)
$wsDash.Cells['A1'].Style.HorizontalAlignment = [OfficeOpenXml.Style.ExcelHorizontalAlignment]::Center
$wsDash.Cells['A1'].Style.Fill.PatternType = [OfficeOpenXml.Style.ExcelFillStyle]::Solid
$wsDash.Cells['A1'].Style.Fill.BackgroundColor.SetColor($darkBlue)
$wsDash.Row(1).Height = 28

# KPI tiles row 1
Add-KpiTile -Worksheet $wsDash -Row 3 -Col 1 -Title 'Total VMs'         -Value $totalVMs        -BgColor $midBlue -TextColor $white
Add-KpiTile -Worksheet $wsDash -Row 3 -Col 2 -Title 'Running VMs'       -Value $runningVMs      -BgColor $green   -TextColor $white
Add-KpiTile -Worksheet $wsDash -Row 3 -Col 3 -Title 'Deallocated VMs'   -Value $deallocatedVMs  -BgColor $red     -TextColor $white
Add-KpiTile -Worksheet $wsDash -Row 3 -Col 4 -Title 'Total Disks'       -Value $totalDisks      -BgColor $gray    -TextColor $white
Add-KpiTile -Worksheet $wsDash -Row 3 -Col 5 -Title 'Unattached Disks'  -Value $unattachedDisks -BgColor $orange  -TextColor $white
Add-KpiTile -Worksheet $wsDash -Row 3 -Col 6 -Title 'Subscriptions'     -Value $subscriptionCnt -BgColor $purple  -TextColor $white

# KPI tiles row 2
Add-KpiTile -Worksheet $wsDash -Row 7 -Col 1 -Title 'VM Compute / Mo'   -Value $vmMonthlyCost   -BgColor $midBlue -TextColor $white
Add-KpiTile -Worksheet $wsDash -Row 7 -Col 2 -Title 'Disk Cost / Mo'    -Value $diskMonthlyCost -BgColor $gray    -TextColor $white
Add-KpiTile -Worksheet $wsDash -Row 7 -Col 3 -Title 'Total Cost / Mo'   -Value $totalMonthlyCost -BgColor $green  -TextColor $white
Add-KpiTile -Worksheet $wsDash -Row 7 -Col 4 -Title 'Dealloc Waste /Mo' -Value $deallocatedWaste -BgColor $red    -TextColor $white
Add-KpiTile -Worksheet $wsDash -Row 7 -Col 5 -Title 'Annual Estimate'   -Value $annualEstimate   -BgColor $purple -TextColor $white

for ($c = 1; $c -le 6; $c++) {
    $wsDash.Column($c).Width = 20
}

# Format KPI values as currency where needed
foreach ($addr in @('A8','B8','C8','D8','E8')) {
    $wsDash.Cells[$addr].Style.Numberformat.Format = '$#,##0.00'
}

# Section titles
$wsDash.Cells['A12'].Value = 'Cost by Subscription'
$wsDash.Cells['A12'].Style.Font.Bold = $true
$wsDash.Cells['A12'].Style.Font.Size = 14

$wsDash.Cells['F12'].Value = 'Top 10 Most Expensive VMs'
$wsDash.Cells['F12'].Style.Font.Bold = $true
$wsDash.Cells['F12'].Style.Font.Size = 14

$wsDash.Cells['A28'].Value = 'Top VM Sizes by Spend'
$wsDash.Cells['A28'].Style.Font.Bold = $true
$wsDash.Cells['A28'].Style.Font.Size = 14

# Dashboard tables
$null = $costBySubscription | Export-Excel -ExcelPackage $pkg -WorksheetName 'Dashboard' -StartRow 13 -StartColumn 1 -AutoSize -AutoFilter -TableName 'DashSubCosts' -TableStyle 'Medium2'
$null = $topExpensiveVMs    | Export-Excel -ExcelPackage $pkg -WorksheetName 'Dashboard' -StartRow 13 -StartColumn 6 -AutoSize -AutoFilter -TableName 'DashTopVMs'   -TableStyle 'Medium9'
$null = ($costByVmSize | Select-Object -First 10) | Export-Excel -ExcelPackage $pkg -WorksheetName 'Dashboard' -StartRow 29 -StartColumn 1 -AutoSize -AutoFilter -TableName 'DashVmSizes' -TableStyle 'Medium6'

# VM Inventory
$null = $vmList | Export-Excel -ExcelPackage $pkg -WorksheetName 'VM Inventory' -AutoSize -AutoFilter -FreezeTopRow -BoldTopRow -TableName 'VMInventory' -TableStyle 'Medium9'
$wsVM = $pkg.Workbook.Worksheets['VM Inventory']
$vmHeaders = @($vmList[0].PSObject.Properties.Name)
$vmLastRow = $vmList.Count + 1
Set-CurrencyColumns -Worksheet $wsVM -Headers $vmHeaders -Columns @('VMHourlyPrice_USD','VMMonthlyPrice_USD','EstTotalDiskCost_USD','EstTotalMonthlyCost_USD') -Format '$#,##0.00'

$powerIdx = [array]::IndexOf($vmHeaders, 'PowerState')
if ($powerIdx -ge 0) {
    $col = Get-ExcelColumn ([int]($powerIdx + 1))
    $range = "${col}2:${col}${vmLastRow}"
    Add-ConditionalFormatting -Worksheet $wsVM -Address $range -RuleType ContainsText -ConditionValue 'running'     -BackgroundColor ([System.Drawing.Color]::LightGreen)
    Add-ConditionalFormatting -Worksheet $wsVM -Address $range -RuleType ContainsText -ConditionValue 'deallocated' -BackgroundColor ([System.Drawing.Color]::LightCoral)
    Add-ConditionalFormatting -Worksheet $wsVM -Address $range -RuleType ContainsText -ConditionValue 'stopped'     -BackgroundColor ([System.Drawing.Color]::LightYellow)
}

$totalIdx = [array]::IndexOf($vmHeaders, 'EstTotalMonthlyCost_USD')
if ($totalIdx -ge 0) {
    $col = Get-ExcelColumn ([int]($totalIdx + 1))
    $range = "${col}2:${col}${vmLastRow}"
    Add-ConditionalFormatting -Worksheet $wsVM -Address $range -RuleType GreaterThan -ConditionValue 1000 -BackgroundColor ([System.Drawing.Color]::FromArgb(255,230,153))
}

# Disk Inventory
$null = $diskList | Export-Excel -ExcelPackage $pkg -WorksheetName 'Disk Inventory' -AutoSize -AutoFilter -FreezeTopRow -BoldTopRow -TableName 'DiskInventory' -TableStyle 'Medium6'
$wsDisk = $pkg.Workbook.Worksheets['Disk Inventory']
$diskHeaders = @($diskList[0].PSObject.Properties.Name)
$diskLastRow = $diskList.Count + 1
Set-CurrencyColumns -Worksheet $wsDisk -Headers $diskHeaders -Columns @('EstMonthlyPrice_USD') -Format '$#,##0.00'

$diskTypeIdx = [array]::IndexOf($diskHeaders, 'DiskType')
if ($diskTypeIdx -ge 0) {
    $col = Get-ExcelColumn ([int]($diskTypeIdx + 1))
    $range = "${col}2:${col}${diskLastRow}"
    Add-ConditionalFormatting -Worksheet $wsDisk -Address $range -RuleType ContainsText -ConditionValue 'OS Disk'   -BackgroundColor ([System.Drawing.Color]::LightSteelBlue)
    Add-ConditionalFormatting -Worksheet $wsDisk -Address $range -RuleType ContainsText -ConditionValue 'Data Disk' -BackgroundColor ([System.Drawing.Color]::LightCyan)
}

$diskStateIdx = [array]::IndexOf($diskHeaders, 'DiskState')
if ($diskStateIdx -ge 0) {
    $col = Get-ExcelColumn ([int]($diskStateIdx + 1))
    $range = "${col}2:${col}${diskLastRow}"
    Add-ConditionalFormatting -Worksheet $wsDisk -Address $range -RuleType ContainsText -ConditionValue 'Unattached' -BackgroundColor ([System.Drawing.Color]::LightCoral)
}

# Cost by Subscription
$null = $costBySubscription | Export-Excel -ExcelPackage $pkg -WorksheetName 'Cost by Subscription' -AutoSize -AutoFilter -FreezeTopRow -BoldTopRow -TableName 'CostBySubscription' -TableStyle 'Medium4'
$wsSub = $pkg.Workbook.Worksheets['Cost by Subscription']
$subHeaders = @($costBySubscription[0].PSObject.Properties.Name)
Set-CurrencyColumns -Worksheet $wsSub -Headers $subHeaders -Columns @('VMCost_USD','DiskCost_USD','TotalCost_USD') -Format '$#,##0.00'
$subTotalIdx = [array]::IndexOf($subHeaders, 'TotalCost_USD')
if ($subTotalIdx -ge 0) {
    $col = Get-ExcelColumn ([int]($subTotalIdx + 1))
    $range = "${col}2:${col}$($costBySubscription.Count + 1)"
    Add-ConditionalFormatting -Worksheet $wsSub -Address $range -DataBarColor ([System.Drawing.Color]::SteelBlue)
}

# Cost by Region
$null = $costByRegion | Export-Excel -ExcelPackage $pkg -WorksheetName 'Cost by Region' -AutoSize -AutoFilter -FreezeTopRow -BoldTopRow -TableName 'CostByRegion' -TableStyle 'Medium7'
$wsRegion = $pkg.Workbook.Worksheets['Cost by Region']
$regionHeaders = @($costByRegion[0].PSObject.Properties.Name)
Set-CurrencyColumns -Worksheet $wsRegion -Headers $regionHeaders -Columns @('VMCompute_USD','TotalMonthly_USD') -Format '$#,##0.00'

# Cost by VM Size
$null = $costByVmSize | Export-Excel -ExcelPackage $pkg -WorksheetName 'Cost by VM Size' -AutoSize -AutoFilter -FreezeTopRow -BoldTopRow -TableName 'CostByVMSize' -TableStyle 'Medium5'
$wsSize = $pkg.Workbook.Worksheets['Cost by VM Size']
$sizeHeaders = @($costByVmSize[0].PSObject.Properties.Name)
Set-CurrencyColumns -Worksheet $wsSize -Headers $sizeHeaders -Columns @('TotalCost_USD','AvgCost_USD') -Format '$#,##0.00'

# Savings Opportunities
if ($savings.Count -gt 0) {
    $null = $savings | Export-Excel -ExcelPackage $pkg -WorksheetName 'Savings Opportunities' -AutoSize -AutoFilter -FreezeTopRow -BoldTopRow -TableName 'SavingsOps' -TableStyle 'Medium10'
    $wsSav = $pkg.Workbook.Worksheets['Savings Opportunities']
    $savHeaders = @($savings[0].PSObject.Properties.Name)
    Set-CurrencyColumns -Worksheet $wsSav -Headers $savHeaders -Columns @('EstTotalDiskCost_USD') -Format '$#,##0.00'
} else {
    $wsSav = Add-Worksheet -ExcelPackage $pkg -WorksheetName 'Savings Opportunities'
    $wsSav.Cells['A1'].Value = 'No deallocated VMs with disk cost found.'
    $wsSav.Cells['A1'].Style.Font.Bold = $true
}

Close-ExcelPackage $pkg
Write-Host "[DONE] Dashboard saved to: $OutputPath" -ForegroundColor Green
